# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - todos-gittest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://kiridharan.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b0f2b35cefe64680b1468b924bfd60cb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2578dc6bfb4441dfbfa0070ce3e38079 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kiridharan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b0f2b35cefe64680b1468b924bfd60cb }}/todo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'todos-gittest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_36e1cb16d0b9414f88611f12240aa06f }}
        images: 'kiridharan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b0f2b35cefe64680b1468b924bfd60cb }}/todo:${{ github.sha }}'